FROM scratch

# Bundle app 
ADD build/rng /

# Add certificates
ADD ./certs/ca.crt /certs/ca.crt
ADD ./certs/rng_50052.key /certs/rng_50052.key
ADD ./certs/rng_50052.crt /certs/rng_50052.crt

EXPOSE 50052

ENTRYPOINT ["/rng"]
CMD ["-cert=/certs/rng_50052.crt", "-key=/certs/rng_50052.key", "-ca=/certs/ca.crt", "-certhostname=rng"]

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VERSION
LABEL org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.name="DockerCoins Go Random String Service" \
    org.label-schema.description="Service to generate a random string" \
    org.label-schema.url="https://github.com/richardcase/dockercoinsgo" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/richardcase/dockercoinsgo" \
    org.label-schema.vendor="Richard Case" \
    org.label-schema.version=$VERSION \
    org.label-schema.schema-version="1.0"