apiVersion: v1
kind: Service
metadata:
  labels:
    app: rng
    tier: backend
  name: rng
spec:
  ports:
    - port: 50052
      protocol: TCP
      targetPort: 50052
  selector:
    app: rng
    tier: backend
  sessionAffinity: None
  type: NodePort